
export const actions ={
    CHECKIN: 'CHECKIN',
    SHOWLOTS: 'SHOWLOTS',
    CHECKOUT: 'CHECKOUT',
    FIND: 'FIND',
    INIT:'INIT',

    RESET :'RESET',
    
    SET_LOTS: 'SET_LOTS',
    SET_INIT: 'SET_INIT',
    SET_CHKIN: 'SET_CHKIN',
    SET_CHKOUT: 'SET_CHKOUT',
    SET_FIND: 'SET_FIND',

    RESET_LOTS: 'RESET_LOTS',
    RESET_INIT: 'RESET_INIT',
    RESET_CHKIN: 'RESET_CHKIN',
    RESET_CHKOUT: 'RESET_CHKOUT',
    RESET_FIND: 'RESET_FIND'
}